### ISSUE TITLE
GitHub Pages Backend Possibilities

### ISSUE THREAD

**Issue by jbeatty88** [Interactive-Phylogeny-Team/InteractivePhylogeny#12]
With GitHub pages, how can we have the backend and frontend running simultaneously? 

We want the front and back end to communicate via REST API which means that both will need to be running separately.

@jbeatty88 and @erikhuck  will research this topic and report

**Comment by erikhuck** [comment]
@jbeatty88 Because of this issue, I'll hold off on setting up the project structure as far as separating the front end and back end into separate directories because it looks like we'll possibly want to set up two separate repositories for the front end and back end. In that case, we might as well make this repo the front end and I can create a second repo for the backend. I'd be happy to set up the most basic express app in a second repo which we can use as a proof of concept. We'll need to determine if GitHub Pages allows us to run two repositories simultaneously, or if we're only allowed one per organization (or some similar restriction). But if we can run two different apps at the same time, we can verify that the front end app and the back end app that I make are able to communicate with each other. Once that's verified, I see no reason not to continue doing that.

**Comment by erikhuck** [comment]
@jbeatty88 If we do end up creating a second repo for the backend, I'd love to learn for myself the process for getting it set up with GitHub Pages.

**Comment by erikhuck** [comment]
@jbeatty88 According to https://pages.github.com, we "get one site per GitHub account and organization, 
and unlimited project sites". It looks like you set up this repo as a "project site"??? If so, we can possibly create another repo for the back end and make it a project site as well. That way we have two sites that can potentially communicate with each other. But the GitHub pages documentation doesn't appear to show how we can run node. How'd you get GitHub to run `npm start` for the react.js app?

**Comment by jbeatty88** [comment]
Development for this project will happen locally. We will not be hosting this project on any hosting providers; this is subject to change.
