### ISSUE TITLE
DNA

### ISSUE THREAD

**Issue by maddyras** [Interactive-Phylogeny-Team/InteractivePhylogeny#15]
We should decide how we want to use/display the DNA:
- Will the tree be generated using DNA sequences?
- If so, how are we going to choose which sequences to use? Because we can't realistically use the whole genome.
- How many nucleotides should we use/display?
- What will be most useful/convenient for our audience?

**Comment by erikhuck** [comment]
@maddyras In one of the papers I read, I learned about something called an orthologous gene. This is described in more detail here: https://sciencing.com/difference-between-orthologous-paralogous-genes-18612.html. Basically it's a gene that's homologous because it is shared between related species but it diverged after a speciation event. Since phylogenetic trees are constructed based off of detecting speciation within homologous genes, it seems like displaying the sequence in a homologous gene would make sense. The paper also mentioned key orthologous genes that have been traditionally used for phylogeny.

**Comment by maddyras** [comment]
I found some sequences that align for the great apes (mitochondrial D-loop).

**Comment by maddyras** [comment]
Josh found a way to visualize the DNA sequences and their differences (dashbio).

**Comment by jbeatty88** [comment]
@maddyras will be selecting DNA sequence data from FASTA files as plain-text.
